django project/market/accounts/urls.py
from django.urls import path
from django.urls import path
from . import views

app_name = "accounts_url_app"

urlpatterns = [
    path("signup/", views.signup_def, name="signup_redirect"),
    path("login/", views.login_def, name="login_redirect"),
    path("logout/", views.logout_def, name="logout_redirect"),
]

django project/market/articles/urls.py
from django.urls import path
from . import views

app_name = "articles_urls_app"
urlpatterns = [
    path("", views.home, name="articles_home_page_redirect"),
    path("create/", views.create_article, name="article_create"),
    path("<slugname>/", views.slug_pages, name="articles_slug_page_redirect"),
]

django project/market/market/urls.py
from django.conf.global_settings import MEDIA_ROOT
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", views.home),
    path("about/", views.about),
    path("articles/", include("articles.urls")),
    path("accounts/", include("accounts.urls")),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django project/market/accounts/models.py
from django.db import models

# Create your models here.

django project/market/articles/models.py
from django.db import models
from django.db.models.fields import BLANK_CHOICE_DASH
from django.contrib.auth.models import User


class Artic(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(default="default.png", blank=True)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def abstract(self):
        return self.body[:50] + " ..."

django project/market/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout


def signup_def(request):
    if request.method == "POST":
        form0 = UserCreationForm(request.POST)
        if form0.is_valid():
            form0.save()
            # login
            return redirect("articles_urls_app:articles_home_page_redirect")
    else:
        form0 = UserCreationForm()
    return render(request, "signup.html", {"form1": form0})


def login_def(request):
    if request.method == "POST":
        form0 = AuthenticationForm(data=request.POST)
        if form0.is_valid():
            user_get = form0.get_user()
            login(request, user_get)
            if "next_key" in request.POST:
                return redirect(request.POST.get("next_key"))
            else:
                return redirect("articles_urls_app:articles_home_page_redirect")
    else:
        form0 = AuthenticationForm()
    return render(request, "login.html", {"form1": form0})


def logout_def(request):
    if request.method == "POST":
        logout(request)
        return redirect("articles_urls_app:articles_home_page_redirect")

django project/market/articles/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .models import Artic
from . import form


def home(request):
    ar = Artic.objects.all().order_by("-date")
    args = {"objects_in_artic_models": ar}
    return render(request, "articlehome.html", args)


@login_required(login_url="/accounts/login")
def create_article(request):
    if request.method == "POST":
        create_article_forms = form.Creat_Article_form(request.POST, request.FILES)
        if create_article_forms.is_valid:
            author_var = create_article_forms.save(commit=False)
            author_var.author = request.user
            author_var.save()
            return redirect("articles_urls_app:articles_home_page_redirect")
    else:
        create_article_forms = form.Creat_Article_form()
        args = {"create_article_forms": create_article_forms}
    return render(request, "create_article.html", args)


def slug_pages(request, slugname):
    ar = Artic.objects.get(slug=slugname)
    args = {"slug_in_article_models": ar}
    return render(request, "artile_by_slug.html", args)

django project/market/market/views.py
from django.shortcuts import render, HttpResponse


def home(request):
    return render(request, "home.html")


def about(request):
    return render(request, "about.html")

django project/market/accounts/templates/login.html
{% extends "base.html" %}

{% block content %}
<h1>Login</h1>
<form class="login-form" action="{% url 'accounts_url_app:login_redirect' %}" method="POST">
    {% csrf_token %}
    <div class="mb-3">
        <label for="formGroupExampleInput" class="form-label">Example label</label>
        <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Example input placeholder">
      </div>
      <div class="mb-3">
        <label for="formGroupExampleInput2" class="form-label">Another label</label>
        <input type="text" class="form-control" id="formGroupExampleInput2" placeholder="Another input placeholder">
      </div>
        {% if request.GET.next %}
            <input type="hidden" name="next_key" value="{{request.GET.next}}" >
        {% endif %}
    {{form1}}
    <input type="submit" value="login">
</form>
{% endblock %}

django project/market/accounts/templates/signup.html
{% extends "base.html" %}

{% block content %}
<h1>Sign Up</h1>
<form class="signup-form" action="{% url 'accounts_url_app:signup_redirect' %}" method="POST">
    {{form1}}
    {% csrf_token %}
    <input type="submit" value="signup">
</form>
{% endblock %}

django project/market/articles/templates/articlehome.html
{% extends "base.html" %}

{% block title %}
Articles Home title
{% endblock %}

{% block content %}
<div class="container" >
    <h2>Articles Home header</h2>
    <p>Article Home "P"</p>
    {%for i in objects_in_artic_models %}
        <h3><a href="{% url 'articles_urls_app:articles_slug_page_redirect' slugname=i.slug %}">{{i.title}}</a></h3>
        {%if i.body|length > 50 %}
            <p>{{i.abstract}}</p>
        {%else%}
            <p>{{i.body}}</p>
        {%endif%}
        <h5>{{i.author.username}}</h5>
        <h6><p>{{i.date}}</p></h6>
    {%endfor%}
</div>
{% endblock %}

django project/market/articles/templates/artile_by_slug.html
{% extends "base.html" %}

{% block title %}
Article page for {{slug_in_article_models.slug}}
{% endblock %}

{% block content %}
{% csrf_token %}
<div class="article_by_slug_in_html_0">
    <div class="article_by_slug_in_html_1">
        <p> </p>
        <h3>{{slug_in_article_models.title}}</h3>
        <p> </p>
        <h5>{{slug_in_article_models.body}}</h5>
        <h6><p>{{slug_in_article_models.date}}</p></h6>
        <img src="{{slug_in_article_models.image.url}}" alt="">
    </div>
</div>
{% endblock %}

django project/market/articles/templates/create_article.html
{% extends 'base.html' %}

{% block content %}
    <div class="create_article_html">
        <h1>
            create article page
        </h1>
        <form class="article_form_html" action="{% url 'articles_urls_app:article_create' %}" method="POST" enctype="multipart/form-data">
            {{create_article_forms}}
            {% csrf_token %}
            <input type="submit" value="create">
        </form>
    </div>
{% endblock %}